// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR2SgXaw75nv0XW3-lctVdPZ2XSlGdxS0',
    appId: '1:800860761349:web:b8a8cb799849ce22201b6c',
    messagingSenderId: '800860761349',
    projectId: 'dailytask-f20e7',
    authDomain: 'dailytask-f20e7.firebaseapp.com',
    storageBucket: 'dailytask-f20e7.appspot.com',
    measurementId: 'G-WHJGZZ0SD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZOSB4kX_zOPh2JwrXgI2NQ0g1Gm3DC4Y',
    appId: '1:800860761349:android:221702deb09b470a201b6c',
    messagingSenderId: '800860761349',
    projectId: 'dailytask-f20e7',
    storageBucket: 'dailytask-f20e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl_XuZhGrK9QY2ynBeald-5guVUPxe_EU',
    appId: '1:800860761349:ios:82f296388abc8f0d201b6c',
    messagingSenderId: '800860761349',
    projectId: 'dailytask-f20e7',
    storageBucket: 'dailytask-f20e7.appspot.com',
    iosClientId: '800860761349-egjkrlb7bt736u16tihnq4n5o60j1fd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyTask',
  );
}
